CREATE TABLE "otherTags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "otherTags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item1" varchar NOT NULL,
	"item2" varchar NOT NULL,
	"item3" varchar NOT NULL,
	CONSTRAINT "otherTags_id_unique" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE "userDetails" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "userDetails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"image" varchar NOT NULL,
	"title" varchar NOT NULL,
	"description" varchar NOT NULL,
	CONSTRAINT "userDetails_id_unique" UNIQUE("id")
);
